# -*- coding: utf-8 -*-
"""교보문고 실시간 검색어 및 단어구름.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cg7qqRFcozVz6Xr738qgOFhN3A8jYaMr
"""

# !pip install selenium webdriver-manager wordcloud matplotlib
# !apt-get update -y
# !apt-get install -y chromium-driver fonts-nanum wget curl unzip
# !wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# !dpkg -i google-chrome-stable_current_amd64.deb || apt -y --fix-broken install
# !CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
# wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P /tmp/ && \
# unzip -o /tmp/chromedriver_linux64.zip -d /usr/local/bin/ && \
# chmod +x /usr/local/bin/chromedriver

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import matplotlib.font_manager as fm

# Selenium 설정
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

# WebDriver 실행
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)

# 교보문고 접속 및 실시간 인기 검색어 수집
driver.get("https://www.kyobobook.co.kr/")
time.sleep(2)
driver.find_element(By.CLASS_NAME, "ip_gnb_search").click()
time.sleep(2)

hot_keywords = driver.find_elements(By.CSS_SELECTOR, ".hot_keyword_item .keyword")
keywords = [keyword.text for keyword in hot_keywords]

# 검색어 출력
print("🔍 실시간 인기 검색어 목록:")
for idx, keyword in enumerate(keywords, 1):
    print(f"{idx}. {keyword}")

driver.quit()

# 폰트 경로 등록
font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

# WordCloud 생성 및 시각화
plt.rc('font', family='NanumGothic')
wordcloud = WordCloud(
    font_path=font_path,
    width=800, height=400,
    background_color="white"
).generate(" ".join(keywords))

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("교보문고 실시간 인기 검색어 WordCloud", fontsize=14)
plt.show()